services:
  mysqldb:
    image: mysql:8.0
    ports:
      - 3399:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=dev
      - MYSQL_USER=appdev
      - MYSQL_PASSWORD=appdev
    volumes:
      - /home/pcwadm/Docker/mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 8080:80
    restart: always
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_USER: appdev
      PMA_PASSWORD: appdev
